---
title: "Review of Clark Proposal"
format: pdf
author: Fred Boehm
date: today
---

## Factor 1: Importance of the Research (Significance, Innovation), scored 1-9

The applicant successfully motivates the research. Alveolar biology has 
many implications in health and disease. I'm quite excited by the research area.




"Organoid" was not defined early in the application. What exactly is it? Why is it needed instead of, for example, 
a real organ? 







## Factor 2: Rigor and Feasibility (Approach), scored 1-9

I would have appreciated more details about the preliminary data. What exactly are they? 
How did the applicant obtain them? Are there figures to summarize the preliminary data? 

I am confused about the proposed timeline. The applicant shows in Figure 7 a three-year timeline, yet discusses a two-year timeline in the body of the text. It might be ambitious
to complete the activities in two years, but reasonable for three years.

I like that the timeline includes both research and professional development activities. 













## Factor 3: Expertise and Resources (Investigator, Environment), to be evaluated as either sufficient for the proposed research or not (in which case reviewers must provide an explanation)


While the applicant's biosketch is unavailable, the applicant is a graduate trainee at 
the University of Michigan, so I expect that the applicant has a strong background 
in molecular biology. 

Given that the applicant is proposing research in a well funded and highly productive 
biology department at the University of Michigan, I expect that the research environment 
is excellent. The department's resources are world-class.

**I think that the expertise and resources are sufficient for the proposed research.**

## Overall Impact

Likely to be high, but I would be more enthused if the applicant had provided some details that, in my view, are missing.


